### ISSUE TITLE
Passare a HTTP POST per richieste a Arkimet

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/agrolib#1]
Abbiamo riabilitato temporaneamente le richieste HTTP GET per estrarre i dati dall'archivio (arpa-simc/arkimet#289), ma vorremmo renderle obsolete. Si dovrebbe dunque passare a fare delle HTTP POST, in cui in parametri rimangono gli stessi ma sono passati come payload.

**Comment by ftomei** [comment]
Ho accettato la pull request e aggiornato il codice perché una funzione era obsoleta. Testato su praga, funziona bene: c'è un nuovo tag (1.5.4) di praga da installare.
